name: recape_sp_front
description: Projeto de Cadastro de Obras de Recape da Intelicity.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
        sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_modular: ^6.3.3
  dio: ^5.1.1
  hive_flutter: ^1.1.0
  mockito: ^5.4.0
  dartz: ^0.10.1
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.4
  file_picker: ^5.3.3
  mask_text_input_formatter: ^2.5.0
  universal_html: ^2.2.3
  image_picker: ^1.0.4
  excel: ^2.1.0
  file_saver: ^0.2.8
  syncfusion_flutter_datagrid: ^24.2.7
  syncfusion_flutter_core: ^24.2.7
  flutter_map_geojson: ^1.0.6
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.6
  http: ^1.2.1
  logger: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  mobx_codegen: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

scripts:
  build: flutter pub run build_runner build
  watch: flutter pub run build_runner watch --delete-conflicting-outputs

flutter_intl:
  enabled: true